config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :order_items
  
  resources :charges

  
  resources :restaurants do
    # resources :menu_categories do
    resources :menu_items
    resources :menu_categories
    resources :orders
    # end
  end
  
  
  root 'restaurants#index'

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id            :integer          not null, primary key
#  total_price   :decimal(, )
#  paid          :datetime
#  fulfilled     :datetime
#  user_id       :integer
#  restaurant_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  has_many :orderitems, class_name: OrderItem.name

  validates :total_price, presence: true,
                          numericality: true

  def mark_as_paid
    self.paid = Time.zone.now
    self.save
  end
  
  def mark_as_fulfilled
    self.fulfilled = Time.zone.now
    self.save
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @restaurant = Restaurant.find(params[:restaurant_id])
    @orders = @restaurant.orders.where(fulfilled: nil).where('total_price > ?', 0)
  end

  def show
    @order = Order.find(params[:id])
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def update
    order = Order.find(params[:id])
    order.mark_as_fulfilled
    redirect_to restaurant_orders_path(params[:restaurant_id])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order.html.erb
<tr>
  <td><%= order.id %></td>
  <td><%= order.user.email %></td>
  <td><%= order.updated_at.strftime("%l:%M %P %b %-d, %Y") %></td>
  <td class="text-center">
    <%= order.paid ? "Yes" : "No" %>
  </td>
  <td class="text-center">
    <%= order.fulfilled ? "Yes" : "No" %>
  </td>
  <td>
    <%= link_to "Details", restaurant_order_path(@restaurant,order) %>
  </td>
</tr>

app/views/orders/index.html.erb
<h2 class="text-center">Pending Orders for <%= @restaurant.name %></h2>
<section id="orders">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <% if @orders.any? %>
        <table class="table table-striped">
          <tr>
            <th>Order No</th>
            <th>From</th>
            <th>Time</th>
            <th class="text-center">Paid</th>
            <th class="text-center">Fulfilled</th>
            <th></th>
          </tr>
          <%= render @orders %>
        </table>
      <% else %>
        <div class="well">
          There are no orders pending.
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/orders/show.html.erb
<section id="orders">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      
      <h2>Order Details for <%= @order.user.email %></h2>
      
      <table class="table">
          <tr>
            <th>Item</th>
            <th class="text-right">Rs</th>
            <th class="text-right">Quantity</th>
          </tr>
        <% @order.orderitems.each do |item| %>
          <tr>
            <td><%= item.menu_item.name %></td>
            <td class="text-right"><%= item.price %></td>
            <td class="text-right"><%= item.quantity %></td>
          </tr>
        <% end %>
        <tr>
          <td><h4>Order Total</h4></td>
          <td class="text-right"><h4><%= "#{@order.total_price}" %></h4></td>
          
          <td class="text-right"><%= link_to "Mark as Fulfilled", restaurant_order_path(@restaurant, @order), method: :patch, class: "btn btn-danger" %></td>
        </tr>
      </table>
      
    </div>
  </div>
</section>