config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :order_items
  
  resources :charges

  
  resources :restaurants do
    # resources :menu_categories do
    resources :menu_items
    resources :menu_categories
    resources :orders
    # end
  end
  
  
  root 'restaurants#index'

end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Restaurant < ActiveRecord::Base
  has_many :menucategories, class_name: MenuCategory.name
  has_many :orders, class_name: Order.name
  has_many :managerships, class_name: Manager.name, dependent: :destroy
  has_many :managers, through: :managerships, source: :user

  validates :name, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :auth, only: [:edit]

  def index
    @restaurants = Restaurant.all
  end

  def show
    # Menu
    @restaurant = Restaurant.find(params[:id])
    @menucategories = @restaurant.menucategories.all
    @menu_item = MenuItem.new

    # Order
    if current_user
      @order = current_user.current_order(@restaurant)
      @orderitems = @order.orderitems
      @total_price = @order.total_price
    end

  end

  def edit
    @restaurant = Restaurant.find(params[:id])
 
    # Menu
    @menucategories = @restaurant.menucategories.all
    @menu_item = MenuItem.new

    # Category
    @category = MenuCategory.new
    
    
  end

private

  def auth
    @restaurant = Restaurant.find(params[:id])
    if !Manager.where(user_id: current_user.id).where(restaurant_id: @restaurant.id).any?
      flash[:alert] = 'You are not authoroised to manage this restaurant'
      redirect_to @restaurant
    end
    
  end
  
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_restaurant.html.erb
<div class="col-md-4">
  <div class="well">
  <%= link_to restaurant.name, restaurant_path(restaurant.id) %>
  </div>
</div>

app/views/restaurants/_stripe.html.erb
<%= simple_form_for @order, url: charges_path, method: 'POST' do |f| %>

  <%= f.input :total_price, as: :hidden %>
  <%= f.input :restaurant_id, as: :hidden %>
  <%= f.input :id, as: :hidden %>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Test purchase from umenu"
          data-amount= <%= @total_price * 100 %>
          data-currency="gbp"
          data-locale="auto">
          </script>
<% end %>

app/views/restaurants/edit.html.erb
<!-- Button trigger modal -->
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2>
        <%= @restaurant.name %>: Edit Menu
      </h2>
      
      <div>
        <% @menucategories.each do |category| %>
          <table class="table table-condensed">
          <%= simple_form_for [@restaurant, category] do |f| %>
            <tr>
              <th>
                <%= f.input :name, label: false %>
              </th>
              <th>
                <%= f.button :submit, "Update", class: "btn-sm" %>
              </th>
            </tr>
          <% end %>
            <% category.menuitems.each do |item| %>
              <%= simple_form_for [@restaurant, item] do |f| %>
                <tr>
                  <td><%= f.input :name, label: false %></td>
                  <td><%= f.input :description, label: false %></td>
                  <td class="medium-column"><%= f.input :price, label: false %></td>
                  <td><%= f.button :submit, "Update", class: "btn-sm" %></td>
                  <td>
                    <%= link_to "x", restaurant_menu_item_path(@restaurant, item), method: :delete, class: "btn-sm btn btn-danger" %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </table>
        <% end %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="well text-center">
        <h2>Add Items</h2>
        <p><%= button_tag "Add Category", class: "btn btn-primary", data: {toggle: "modal", target:"#addCategory"} %></p>
        <p><%= button_tag "Add Menu Item", class: "btn btn-primary", data: {toggle: "modal", target:"#addItem"} %></p>
      </div>
    </div>
  </div>
</div>

<!-- Modal Add Item -->
<div class="modal fade" id="addItem" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Menu Item</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@restaurant, @menu_item] do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :menucategory, label: "Category", collection: @menucategories, as: :radio_buttons, label_method: :name, value_method: :id %>
          <%= f.button :submit, "Add Item" %>
        <% end %>
       
      </div>
    </div>
  </div>
</div>

<!-- Modal Add Category -->
<div class="modal fade" id="addCategory" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Category</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@restaurant, @category] do |f| %>
          <%= f.input :name %>
          <%= f.button :submit, "Add Category" %>
        <% end %>
       
      </div>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="well">
      
      <h2>
        <%= @restaurant.name %>
      </h2>
      
        <table class="table">
        <% @menucategories.each do |category| %>
          <tr class="menu-category">
            <th><h3><%= category.name %></h3></th>
            <th class="text-center">Rs.</th>
            <th class="text-center"></th>
          </tr>
              <% category.menuitems.each do |item| %>
              <tr>
                <td>
                  <%= item.name %>
                  <p class="item-description"><%= item.description %></p>
                </td>
                <td class="text-center"><%= "#{item.price}" %></td>
                <% if current_user %>
                  <td class="text-center">
                    <%= link_to '', order_items_path(item: item, restaurant: @restaurant), class: "fa fa-plus-circle", method: :post, remote: true %>
                  </td>
                <% end %>
              </tr>
              <% end %>
        <% end %>
        </table>
      </div>
    </div>
    <% if current_user %>
      <div class="col-md-6">
        
          <% if @orderitems.any? %>
            <%= render 'order_items/order_form' %>
          <% else %>
            <%= render 'order_items/order_teaser' %>
          <% end %>
        
      </div>
    <% else %>
      <div class="col-md-6 text-center">
        <div class="well">
          <h2>Your Order</h2>
          <p>
            <%= link_to "Sign In To Order", new_user_session_path, class: "btn btn-primary btn-lge" %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>