config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :order_items
  
  resources :charges

  
  resources :restaurants do
    # resources :menu_categories do
    resources :menu_items
    resources :menu_categories
    resources :orders
    # end
  end
  
  
  root 'restaurants#index'

end

app/models/order_item.rb
# == Schema Information
#
# Table name: order_items
#
#  id           :integer          not null, primary key
#  price        :decimal(, )
#  quantity     :integer
#  request      :string
#  order_id     :integer
#  menu_item_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :menu_item

  validates :quantity,  presence: true,
                        numericality: true
  validates :price,     presence: true,
                        numericality: true
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  respond_to :html, :js

  def create
    item = MenuItem.find(params[:item])
    restaurant = Restaurant.find(params[:restaurant])
    @order_item = current_user.add_to_order(item, restaurant)
    @order = @order_item.order
    @total_price = @order.total_price
    @quantity = @order_item.quantity
    @orderitems = @order.orderitems
  end

  def destroy
    
    @order_item = OrderItem.find(params[:id])
    @order = @order_item.order
    amount = @order_item.price
    if @order_item.quantity == 1
      @order_item.destroy
      @quantity = 0
    else
      @order_item.quantity -= 1
      @quantity = @order_item.quantity
      @order_item.save
    end


    
    @order_item.order.total_price -= amount
    @total_price = @order_item.order.total_price
    @order_item.order.save


  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_order_form.html.erb
<div id="order-form">
  <h2>Your Order</h2>
              
  <table id="live-order" class="table">
      
        <%= render 'order_items/order_total' %>
        
      <tr>
        <th>Item</th>
        <th class="text-center slim-column">Rs.</th>
        <th class="text-center slim-column">Qty</th>
        <th class="text-center"></th>
      </tr>
      <%= render @orderitems %>
      
  </table>
</div>

app/views/order_items/_order_item.html.erb
<tr id="<%= dom_id(order_item) %>">
  <td><%= order_item.menu_item.name %></td>
  <td class="text-center"><%= order_item.price %></td>
  <td id="quantity" class="text-center"><%= order_item.quantity %></td>
  <td><%= link_to '', order_item_path(order_item), class: "fa fa-minus-circle remove", method: :delete, remote: true %></td>
</tr>

app/views/order_items/_order_teaser.html.erb
<div id="order-teaser">
  <h2>Feeling hungry?</h2>
  <p>Order some great food from our new menu!</p>
</div>

app/views/order_items/_order_total.html.erb
<tr id="live-order-total">
  <td class="wide-column"><h4>Order Total</h4></td>
  <td colspan="2"><h4><%= "Rs. #{@total_price}" %></h4></td>
  <td class="text-right"><%= render 'restaurants/stripe' %></td>
</tr>

app/views/order_items/create.js.erb
if ( $('#order-teaser').length ) {
  $('#order-teaser').replaceWith('<%= j render('order_items/order_form') %>');
} else {
  <% if @quantity == 1 %>
    // $('#live-order').append('<%= j render(@order_item) %>').show('slow');
    $('<%= j render(@order_item) %>').hide().appendTo('#live-order').show(250);
  <% else %>
    $('#<%= dom_id(@order_item) %>').replaceWith('<%= j render(@order_item) %>');
    $('#<%= dom_id(@order_item) %> #quantity').effect("highlight", {color: '#93C54B'}, 500);
  <% end %>
};

$('#live-order-total').replaceWith('<%= j render('order_total') %>');
$('.stripe-button').data('amount', '<%= @total_price %>');

app/views/order_items/destroy.js.erb
<% if @quantity == 0 %>
  $('#<%= dom_id(@order_item) %>').effect("fade", {}, 250);
<% else %>
  $('#<%= dom_id(@order_item) %>').replaceWith('<%= j render(@order_item) %>');
  $('#<%= dom_id(@order_item) %> #quantity').effect("highlight", {color: '#d9534f'}, 500);
<% end %>

$('#live-order-total').replaceWith('<%= j render('order_total') %>');