config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :order_items
  
  resources :charges

  
  resources :restaurants do
    # resources :menu_categories do
    resources :menu_items
    resources :menu_categories
    resources :orders
    # end
  end
  
  
  root 'restaurants#index'

end

app/views/common/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "umenu", root_path, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Order", restaurant_path(1) %></li>
          <% if !current_user %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
          <% else %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Manage Menu", edit_restaurant_path(1) %></li>
              <li><%= link_to "Manage Orders", restaurant_orders_path(1) %></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>